# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
aka = User.create(name: 'Aka', photo: 'https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png', bio: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.')
paka = User.create(name: 'Paka', photo: 'https://www.kindpng.com/picc/m/24-248253_user-profile-default-image-png-clipart-png-download.png', bio: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.')

aka_first_post = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.
  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:aka)

aka_second_post = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.
  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:aka)

aka_third_post = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.
  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:aka)



paka_first_post = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.
  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:paka)

paka_second_post = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.
  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:paka)

paka_third_post = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.
  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:paka)
