# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

juliana = User.create(name: 'Juliana', photo: 'http://www.pselaw.com/wp-content/uploads/2016/08/pokemon-150x150.jpg', bio: 'Hello! My name is Juliana and I\'m a full-stack software developer. I’m currently completing coursework at Microverse, a remote software development school that uses pair programming and real-world projects to teach development.
  I\'ve spent the last several months completely immersed in remote development, building real-world projects, and at the same time grooming my soft skills like time management and being able to collaborate and work with different developers across the globe.')

juliana_post_one = Post.create(title: "Lorem ipsum dolor sit amet", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:juliana)
juliana_post_two = Post.create(title: "Lorem ipsum dolor sit amet", text: "Etiam et mauris et ligula fringilla fermentum ac vel dui. Praesent a malesuada mauris. Ut maximus est in iaculis luctus. Curabitur vel tempor sem. Nunc sem ligula, condimentum quis velit dignissim, fringilla egestas velit. Nullam efficitur, elit in lacinia sodales, nibh quam facilisis risus, non euismod arcu urna id dui. Nam sit amet sem quis orci consectetur dapibus. Ut condimentum maximus dolor. Integer vel hendrerit ex. Duis finibus nibh quis magna faucibus dignissim. Sed condimentum sodales ullamcorper. Cras nec maximus purus, non gravida sapien. Morbi porttitor laoreet magna, venenatis dignissim tellus consequat vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla nunc sapien, elementum nec aliquam nec, vulputate id libero. Ut tincidunt tellus ac semper finibus.", author:juliana)
juliana_post_three = Post.create(title: "Pellentesque blandit libero non", text: "Etiam et mauris et ligula fringilla fermentum ac vel dui. Praesent a malesuada mauris. Ut maximus est in iaculis luctus. Curabitur vel tempor sem. Nunc sem ligula, condimentum quis velit dignissim, fringilla egestas velit. Nullam efficitur, elit in lacinia sodales, nibh quam facilisis risus, non euismod arcu urna id dui. Nam sit amet sem quis orci consectetur dapibus. Ut condimentum maximus dolor. Integer vel hendrerit ex. Duis finibus nibh quis magna faucibus dignissim. Sed condimentum sodales ullamcorper. Cras nec maximus purus, non gravida sapien. Morbi porttitor laoreet magna, venenatis dignissim tellus consequat vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla nunc sapien, elementum nec aliquam nec, vulputate id libero. Ut tincidunt tellus ac semper finibus.", author:juliana)
juliana_post_four = Post.create(title: "consectetur adipiscing elit", text: "Etiam et mauris et ligula fringilla fermentum ac vel dui. Praesent a malesuada mauris. Ut maximus est in iaculis luctus. Curabitur vel tempor sem. Nunc sem ligula, condimentum quis velit dignissim, fringilla egestas velit. Nullam efficitur, elit in lacinia sodales, nibh quam facilisis risus, non euismod arcu urna id dui. Nam sit amet sem quis orci consectetur dapibus. Ut condimentum maximus dolor. Integer vel hendrerit ex. Duis finibus nibh quis magna faucibus dignissim. Sed condimentum sodales ullamcorper. Cras nec maximus purus, non gravida sapien. Morbi porttitor laoreet magna, venenatis dignissim tellus consequat vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla nunc sapien, elementum nec aliquam nec, vulputate id libero. Ut tincidunt tellus ac semper finibus.", author:juliana)
juliana_post_five = Post.create(title: "ipsum dolor adipiscing elit", text: "Etiam et mauris et ligula fringilla fermentum ac vel dui. Praesent a malesuada mauris. Ut maximus est in iaculis luctus. Curabitur vel tempor sem. Nunc sem ligula, condimentum quis velit dignissim, fringilla egestas velit. Nullam efficitur, elit in lacinia sodales, nibh quam facilisis risus, non euismod arcu urna id dui. Nam sit amet sem quis orci consectetur dapibus. Ut condimentum maximus dolor. Integer vel hendrerit ex. Duis finibus nibh quis magna faucibus dignissim. Sed condimentum sodales ullamcorper. Cras nec maximus purus, non gravida sapien. Morbi porttitor laoreet magna, venenatis dignissim tellus consequat vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla nunc sapien, elementum nec aliquam nec, vulputate id libero. Ut tincidunt tellus ac semper finibus.", author:juliana)

juliana_comment_one =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_one)
juliana_comment_two =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_two)
juliana_comment_three =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_three)
juliana_comment_four =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_four)
juliana_comment_five =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_five)
juliana_comment_six =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_one)
juliana_comment_seven =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_two)
juliana_comment_eight =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_two)
juliana_comment_nine =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_two)
juliana_comment_ten =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_five)
juliana_comment_eleven =  Comment.create(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna", author:juliana, post: juliana_post_one)

juliana_like_one = Like.create(author: juliana, post: juliana_post_one)
juliana_like_two = Like.create(author: juliana, post: juliana_post_two)
juliana_like_three = Like.create(author: juliana, post: juliana_post_five)

dammy = User.create(name: 'Dammy', photo: 'http://www.pselaw.com/wp-content/uploads/2016/08/pokemon-150x150.jpg', bio: 'Hello! My name is Dammy and I\'m a full-stack software developer. I’m currently completing coursework at Microverse, a remote software development school that uses pair programming and real-world projects to teach development.
  I\'ve spent the last several months completely immersed in remote development, building real-world projects, and at the same time grooming my soft skills like time management and being able to collaborate and work with different developers across the globe.')

dammy_post_one = Post.create(title: 'Lorem ipsum dolor sit amet', text: 'Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.', author: dammy)
dammy_post_two = Post.create(title: 'Lorem ipsum dolor sit amet', text: 'Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.', author: dammy)

dammy_comment_one = Comment.create(text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna.', author: dammy, post: dammy_post_one)
dammy_comment_two = Comment.create(text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis ligula eget nisl sodales mollis. Pellentesque blandit libero non urna.', author: dammy, post: dammy_post_two)

dammy_like_one = Like.create(author: dammy, post: dammy_post_one)
dammy_like_two = Like.create(author: dammy, post: dammy_post_two)

quincy = User.create(name:"Quincy", photo: "http://www.pselaw.com/wp-content/uploads/2016/08/pokemon-150x150.jpg", bio: "Hello! My name is Quincy and I'm a full-stack software developer.")

quincy_post_one = Post.create(title: "Lorem ipsum dolor sit amet one", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: quincy)
quincy_post_two = Post.create(title: "Lorem ipsum dolor sit amet two", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: quincy)
quincy_post_three = Post.create(title: "Lorem ipsum dolor sit amet three", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:quincy)
quincy_post_four = Post.create(title: "Lorem ipsum dolor sit amet four", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:quincy)
quincy_post_five = Post.create(title: "Lorem ipsum dolor sit amet five", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author:quincy)

quincy_comment_one = Comment.create(text: "Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia.", author:quincy, post: quincy_post_one)
quincy_comment_two= Comment.create(text: "Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur", author:quincy, post: quincy_post_two)
quincy_comment_three = Comment.create(text:"Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur", author:quincy, post: juliana_post_one)
quincy_comment_four = Comment.create(text:"Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur", author:quincy, post: dammy_post_one)


quincy_like_one = Like.create(author:quincy, post: quincy_post_one)
quincy_like_two = Like.create(author:quincy, post: quincy_post_two)
quincy_like_three = Like.create(author:quincy, post: quincy_post_three)


henry = User.create(name:"Henry", photo: "http://www.pselaw.com/wp-content/uploads/2016/08/pokemon-150x150.jpg", bio: "iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur.")

henry_post_one = Post.create(title: "Fusce iaculis ex condimentum one", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: henry)
henry_post_two = Post.create(title: "Fusce iaculis ex condimentum two", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: henry)
henry_post_three = Post.create(title: "Fusce iaculis ex condimentum three", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: henry)

henry_comment_one = Comment.create(text: "pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetu", author:henry, post: henry_post_one)
henry_comment_two= Comment.create(text: "pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetu", author:henry, post: henry_post_two)
henry_comment_three= Comment.create(text: "pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetu", author:henry, post: henry_post_three)

henry_like_one = Like.create(author:henry, post: henry_post_one)
henry_like_two = Like.create(author:henry, post: henry_post_two)
henry_like_three = Like.create(author:henry, post: henry_post_three)

mercy = User.create(name:"Mercy", photo: "http://www.pselaw.com/wp-content/uploads/2016/08/pokemon-150x150.jpg")

mercy_post_one = Post.create(title: "Fusce iaculis ex condimentum one", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: mercy)
mercy_post_two = Post.create(title: "Fusce iaculis ex condimentum two", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: mercy)
mercy_post_three = Post.create(title: "Fusce iaculis ex condimentum three", text: "Maecenas in dapibus odio. In iaculis turpis vitae pellentesque ultrices. Pellentesque sit amet augue rutrum, viverra leo vel, laoreet turpis. Aenean quis dolor faucibus, sollicitudin nisl at, euismod metus. Sed commodo purus molestie nulla fermentum posuere. Nunc quis cursus mauris, in pellentesque purus. Sed tristique mi ut bibendum placerat.

  Nunc lorem turpis, porttitor nec nunc ut, gravida rhoncus neque. Vestibulum accumsan ultrices nibh vitae lacinia. Fusce iaculis ex condimentum pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetur. Nulla semper, leo sit amet ornare suscipit, libero turpis mattis justo, a lacinia leo dui non erat. Quisque erat massa, ultrices vel aliquam id, iaculis sit amet elit. Praesent eget diam at purus aliquet molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce auctor sem quam. Curabitur nec convallis ligula. Phasellus sed dignissim metus. Integer nibh lacus, tincidunt et ipsum sit amet, gravida posuere ipsum.", author: mercy)

mercy_comment_one = Comment.create(text: "pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetu", author:mercy, post: mercy_post_one)
mercy_comment_two= Comment.create(text: "pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetu", author:mercy, post: mercy_post_two)
mercy_comment_three= Comment.create(text: "pellentesque vestibulum. Curabitur in lectus sit amet felis viverra consectetu", author:mercy, post: mercy_post_three)

mercy_like_one = Like.create(author:mercy, post: mercy_post_one)
mercy_like_two = Like.create(author:mercy, post: mercy_post_two)
mercy_like_three = Like.create(author:mercy, post: mercy_post_three)
